source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'TimeIntervalPicker', :exclusive => true do
  pod "TimeIntervalPicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TimeIntervalPicker", :path => "../"
  pod 'FBSnapshotTestCase'
end
